name: LLM CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1

      - name: Create .env
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > .env

      - name: Install deps
        run: npm ci

      # - name: Run
      #   run: pm2 restart llm
